In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#to computethe backward propagation tensor must know wt all operation it has gone though such that it can easily back propagate 
#meaning all the operation performed must be remembered, to  make this possible we use a gradeianttape
# 1st all the operations are performed under the tape and then differentiation is added to the tape


In [3]:
w=tf.Variable(tf.random.normal((3,2)),name='vin')
b=tf.Variable(tf.zeros(2,dtype=tf.float32),name='tin')
x=[[1,2,3]]
#specifying the foward propagation
with tf.GradientTape(persistent=True) as tape:
    y=x@w+b
    print(y.numpy())
    loss=tf.reduce_mean(y**2)
#descripbing the parameter wtr to which it should be differianted with the loss amount
[dw,db]=tape.gradient(loss,[w,b])

[[-6.40662  -5.777982]]


In [4]:
dw

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ -6.40662 ,  -5.777982],
       [-12.81324 , -11.555964],
       [-19.21986 , -17.333946]], dtype=float32)>

In [5]:
dw.numpy()

array([[ -6.40662 ,  -5.777982],
       [-12.81324 , -11.555964],
       [-19.21986 , -17.333946]], dtype=float32)

In [6]:
(x@dw+db).numpy()

array([[-96.099304, -86.66974 ]], dtype=float32)

In [7]:
#working with layers
layer=tf.keras.layers.Dense(2,activation='sigmoid')
x=tf.constant([[1,2,3]],dtype=tf.float32)
print(layer.trainable_variables)
with tf.GradientTape(persistent=True) as tape:
    y=layer(x)
    print(y.numpy())
    loss=tf.reduce_mean(y**2)
grad=tape.gradient(loss,layer.trainable_variables)

[]
[[0.44414532 0.06830034]]


In [8]:
for var,gra in zip(layer.trainable_variables,grad):
    print(f'{var.name} {gra.numpy()}')

dense/kernel:0 [[0.10965072 0.00434632]
 [0.21930143 0.00869264]
 [0.32895213 0.01303896]]
dense/bias:0 [0.10965072 0.00434632]


In [9]:
#prints all the variables it has worked or changed values upon
#note that we cannot change constant tensor values hence only variables are seen
for var in tape.watched_variables():
    print(var)

<tf.Variable 'dense/kernel:0' shape=(3, 2) dtype=float32, numpy=
array([[-0.30945623,  0.7921095 ],
       [ 0.8597169 , -0.21270597],
       [-0.5447776 , -0.9932643 ]], dtype=float32)>
<tf.Variable 'dense/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>


In [14]:
#to make the tape look on a particular variable use tape.watch(tensor)
with tf.GradientTape(persistent=True) as tp:
    tp.watch(x)
    y=x**3
    z=y*2
gra=tp.gradient(y,x)

In [15]:
gra

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[ 3., 12., 27.]], dtype=float32)>

In [16]:
#reference to the tape is deleted
del tape