In [2]:
import tensorflow as tf

In [3]:
#tf.Variable is used when the values have to be changed in the tensors
a=tf.Variable([1,2,3])

In [4]:
tf.convert_to_tensor(a)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [5]:
a

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>

In [6]:
#all operations same as constant except reshape reshape creates a new tensor
b=tf.reshape(a,[3,1])
print(a)
print(b)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>
tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)


In [7]:
#changing values inside tensor not possible in tf.constant
a.assign([4,5,6])

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([4, 5, 6])>

In [10]:
#each variable tensor can be identified by a name
c=tf.Variable([1,2,3],name='tan')
d=tf.Variable([1,2,3],name='vis')

In [11]:
c==d

<tf.Tensor: shape=(3,), dtype=bool, numpy=array([ True,  True,  True])>