In [14]:
import tensorflow as tf
import numpy as np

In [6]:
#tensor: basic unit on which tensor flow works on tensor is nothing but a n dimentional array
# tf.constant tensors are immutable hence there values cannot be changed

arr=[[1.,2.,3.],[4.,5.,6.]]

In [7]:
tensor= tf.constant(arr)
#can set custome dtype by tf.constant(arr,dtype=tf.float16)

In [8]:
tensor


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [10]:
#tensor has 2 attributes dtype and shape
tensor.dtype
tensor.shape

TensorShape([2, 3])

In [11]:
# mathametical operations can be performed
tensor+tensor
tensor *5

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 5., 10., 15.],
       [20., 25., 30.]], dtype=float32)>

In [12]:
#transpose of tensor
tf.transpose(tensor)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 4.],
       [2., 5.],
       [3., 6.]], dtype=float32)>

In [13]:
tf.concat([tensor,tensor],axis=0)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [18]:
#to convert to numpy array
tensor.numpy()
np.array(tensor)

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [27]:
a=tf.constant([[1,2],[3,4]],dtype=tf.float32)
b=tf.constant([[-1,0],[1,-1]],dtype=tf.float32)

In [28]:
#element wise addidtion subraction multiplication and matrix multiplication using@
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a@b)

tf.Tensor(
[[0. 2.]
 [4. 3.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[2. 2.]
 [2. 5.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-1.  0.]
 [ 3. -4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-1. inf]
 [ 3. -4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 1. -2.]
 [ 1. -4.]], shape=(2, 2), dtype=float32)


In [29]:
#to find largest value in tensor
print(tf.reduce_max(a))
#to find index of largest va;ue
print(tf.math.argmax(a))
#softmax
print(tf.nn.softmax(a))

tf.Tensor(4.0, shape=(), dtype=float32)
tf.Tensor([1 1], shape=(2,), dtype=int64)
tf.Tensor(
[[0.26894143 0.7310586 ]
 [0.26894143 0.7310586 ]], shape=(2, 2), dtype=float32)


In [30]:
#attributes of a tensor
print(a.dtype)
print(a.ndim)#no of axis
print(a.shape)
print(tf.size(a).numpy())#total no of elements

<dtype: 'float32'>
2
(2, 2)
4


In [32]:
#element wise access
a[1,1].numpy()
a[:,0].numpy()

array([1., 3.], dtype=float32)

In [34]:
#reshaping '-1' indicates wtever fits in
print(tf.reshape(a,[1,4]))
print(tf.reshape(a,[4,1]))
print(tf.reshape(a,[-1]))
print(tf.reshape(a,[1,-1]))

tf.Tensor([[1. 2. 3. 4.]], shape=(1, 4), dtype=float32)
tf.Tensor(
[[1.]
 [2.]
 [3.]
 [4.]], shape=(4, 1), dtype=float32)
tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float32)
tf.Tensor([[1. 2. 3. 4.]], shape=(1, 4), dtype=float32)


In [35]:
#broadcasting similar to numpy broadcasts tensors so that size are compatable
c=tf.constant([2],dtype=tf.float32)

In [36]:
a*c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 4.],
       [6., 8.]], dtype=float32)>

In [41]:
#to check how broadcasting is working
tf.broadcast_to(tf.constant([1,2,3]),[4,3])

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])>

In [45]:
#ragged tensor: constant tensor has perfect dimension but when dimensions are different we use ragged tensor
lst=[[1,2,3],[1,2],[1,2,3,4,5]]
tf.ragged.constant(lst)

<tf.RaggedTensor [[1, 2, 3], [1, 2], [1, 2, 3, 4, 5]]>

In [46]:
tf.ragged.constant(lst).shape


TensorShape([3, None])

In [50]:
#tensors can be strings to
tf.constant("hello world").shape

TensorShape([])

In [51]:
tf.constant(["hello world",'pussycat'])

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'hello world', b'pussycat'], dtype=object)>

In [56]:
#sparse matrix only some positions are filled with values
sp=tf.sparse.SparseTensor(indices=[[1,1],[3,2]],values=[15,2],dense_shape=[5,5])

In [57]:
tf.sparse.to_dense(sp)

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0],
       [ 0, 15,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  2,  0,  0],
       [ 0,  0,  0,  0,  0]])>