In [1]:
import tensorflow as tf

In [6]:
#initialization of tenor
x=tf.constant(4,dtype=tf.float64)
y=[[1,2,3],[2,3,4]]
y=tf.constant(y)

In [7]:
tf.ones((3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [8]:
tf.zeros((2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [9]:
tf.eye(3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [11]:
tf.random.normal((4,4),mean=0,stddev=1)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[ 0.86845267, -0.47143182,  0.2807947 ,  0.9433161 ],
       [ 1.557707  ,  0.14563632, -0.38343716, -0.2814034 ],
       [-0.8216129 , -0.08175123,  0.04916924, -0.5802506 ],
       [-1.4905151 ,  0.65443176, -0.5237252 , -1.5199541 ]],
      dtype=float32)>

In [12]:
tf.random.uniform((2,4),minval=0,maxval=1)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0.15059185, 0.76246846, 0.11262417, 0.13439405],
       [0.6248908 , 0.74560094, 0.7669033 , 0.4907918 ]], dtype=float32)>

In [17]:
tf.range(15,45)

<tf.Tensor: shape=(30,), dtype=int32, numpy=
array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])>

In [23]:
x=tf.ones((3,3))*9
y=tf.eye(3)*15

In [24]:
x+y

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[24.,  9.,  9.],
       [ 9., 24.,  9.],
       [ 9.,  9., 24.]], dtype=float32)>

In [25]:
x-y

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-6.,  9.,  9.],
       [ 9., -6.,  9.],
       [ 9.,  9., -6.]], dtype=float32)>

In [26]:
x*y

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[135.,   0.,   0.],
       [  0., 135.,   0.],
       [  0.,   0., 135.]], dtype=float32)>

In [27]:
x/y

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.6, inf, inf],
       [inf, 0.6, inf],
       [inf, inf, 0.6]], dtype=float32)>

In [29]:
tf.reduce_sum(tf.tensordot(x,y,axes=1))#dot product and sum of all elements

<tf.Tensor: shape=(), dtype=float32, numpy=1215.0>

In [31]:
tf.matmul(x,y) #matrix multiply
x@y

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[135., 135., 135.],
       [135., 135., 135.],
       [135., 135., 135.]], dtype=float32)>

In [34]:
x[:,2:-1]

<tf.Tensor: shape=(3, 0), dtype=float32, numpy=array([], shape=(3, 0), dtype=float32)>

In [35]:
tf.reshape(x,(1,9))

<tf.Tensor: shape=(1, 9), dtype=float32, numpy=array([[9., 9., 9., 9., 9., 9., 9., 9., 9.]], dtype=float32)>

In [37]:
from tensorflow import keras
from tensorflow.keras import layers